version: 1

env:
  model_name: Transformer
  recompute:
    "6": 0
  recompute_log_level: WARNING
  project_root: ../../

run:
  task: benchmark

tasks:
  benchmark:
    args: []

  train:
    args: []

  capture:
    args: []

  custom-train:
    args: []

  translate:
    args: []

  zh-en-train:
    args:
      - "--epochs"
      - "20"
      - "--batch-size"
      - "64"
      - "--max-len"
      - "48"
      - "--vocab-size"
      - "5000"

  zh-en-translate:
    args: []
